# cudn.yaml
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: vm3-cudn
spec:
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values: ["vm3"]
  network:
    topology: Layer2
    layer2:
      role: Secondary
      subnets:
        - "10.128.0.0/24"