apiVersion: v1
kind: Secret
metadata:
  name: vm-workload-3-secret
type: Opaque
stringData:
  networkdata: |
    ethernets:
      eth0:
        addresses:
          - 10.128.0.50/24
        gateway4: 10.128.0.1
    version: 2