apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm3
spec:
  dataVolumeTemplates:
    - metadata:
        name: vm3-volume
      spec:
        sourceRef:
          kind: DataSource
          name: centos-stream9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
          storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  instancetype:
    name: u1.medium
  preference:
    name: centos.stream9
  runStrategy: Always
  template:
    metadata:
      labels:
        network.kubevirt.io/heasdlessService: headless
    spec:
      domain:
        devices:
          autoattachPodInterface: false
          disks:
            - bootOrder: 1
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - model: virtio
              name: nic-salmon-guan-58
              state: up
              bridge: {}
      networks:
        - name: nic-salmon-guan-58
          multus:
            networkName: vm3-cudn
      subdomain: headless
      volumes:
        - dataVolume:
            name: vm3-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: tyq2-zgbz-qiw0
              user: centos
            networkDataSecretRef:
              name: vm-workload-3-secret
          name: cloudinitdisk
