apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm3
spec:
  dataVolumeTemplates:
    - metadata:
        name: vm3-volume
      spec:
        sourceRef:
          kind: DataSource
          name: centos-stream9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
          storageClassName: ibmc-vpc-block-10iops-tier
  instancetype:
    name: u1.medium
  preference:
    name: centos.stream9
  runStrategy: Always
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices:
          autoattachPodInterface: false
          disks:
            - bootOrder: 1
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - model: virtio
              name: nic-salmon-guan-58
              state: up
              bridge: {}
      networks:
        - name: nic-salmon-guan-58
          multus:
            networkName: test-cudn
      subdomain: headless
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: vm-3-pvc
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: "#cloud-config"
            networkDataSecretRef: 
              name: vm-workload-3-secret
