apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm5
spec:
  dataVolumeTemplates:
    - metadata:
        name: vm5-volume
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
          storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  instancetype:
    name: u1.medium
  preference:
    name: fedora
  runStrategy: Always
  template:
    metadata:
      labels:
        network.kubevirt.io/heasdlessService: headless
    spec:
      domain:
        devices:
          autoattachPodInterface: false
          disks:
            - bootOrder: 1
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - model: virtio
              name: teszt
              state: up
              bridge: {}
      networks:
        - name: teszt
          multus:
            networkName: vm5-cudn
      subdomain: headless
      volumes:
        - dataVolume:
            name: vm4-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora
          name: cloudinitdisk
