apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: vm4-cudn
spec:
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values: ["vm4"]
  network:
    topology: Layer2
    layer2:
      role: Secondary
      ipam:
        mode: Disabled
